SIMS_IT0602/Controllers/ClassController.cs
using Microsoft.AspNetCore.Mvc;
using SIMS_IT0602.Models;
using System.Security.Claims;
using System.Text.Json;

namespace SIMS_IT0602.Controllers
{
    public class ClassController : Controller
    {
        static List<Class> classes = new List<Class>();
        public List<Class>? LoadClassFromFile(string fileName)
        {
            string readText = System.IO.File.ReadAllText("class.json");
            return JsonSerializer.Deserialize<List<Class>>(readText);
        }
        public IActionResult ViewClass()
        {

            ViewBag.UserName = HttpContext.Session.GetString("UserName");
            ViewBag.Role = HttpContext.Session.GetString("Role");
            // Read a file
            classes = LoadClassFromFile("class.json");
            return View(classes);
            // Trả về view Managestudent.cshtml
            // return View("Managestudent");//
        }
        public IActionResult ManageClass()
        {
            ViewBag.UserName = HttpContext.Session.GetString("UserName");
            ViewBag.Role = HttpContext.Session.GetString("Role");
            // Read a file
            classes = LoadClassFromFile("class.json");
            return View(classes);
            // Trả về view Managestudent.cshtml
            // return View("Managestudent");//
        }
        public IActionResult Delete(int Id)
        {
            var classes = LoadClassFromFile("class.json");

            //find teacher in an array
            var searchClass = classes.FirstOrDefault(t => t.Id == Id);
            classes.Remove(searchClass);

            //save to file
            var options = new JsonSerializerOptions { WriteIndented = true };
            string jsonString = JsonSerializer.Serialize(classes, options);
            //Save file
            using (StreamWriter writer = new StreamWriter("class.json"))
            {
                writer.Write(jsonString);
            }
            return RedirectToAction("ManageClass");
        }
        [HttpPost] //submit new Teacher
        public IActionResult NewClass(Class @class)
        {
            classes.Add(@class);
            var options = new JsonSerializerOptions { WriteIndented = true };
            string jsonString = JsonSerializer.Serialize(classes, options);
            //Save file
            using (StreamWriter writer = new StreamWriter("class.json"))
            {
                writer.Write(jsonString);
            }

            return RedirectToAction("ManageClass", new { classes = jsonString });
        }
        [HttpGet] //click hyperlink
        public IActionResult NewClass()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Edit(Class @class)
        {
            var existingClass = classes.FirstOrDefault(t => t.Id == @class.Id);
            if (existingClass == null)
            {
                return NotFound(); // Trả về lỗi 404 nếu không tìm thấy giáo viên
            }
            existingClass.ClassName = @class.ClassName;
            existingClass.Major = @class.Major;
            existingClass.Lecturer = @class.Lecturer;

            var options = new JsonSerializerOptions { WriteIndented = true };
            string jsonString = JsonSerializer.Serialize(classes, options);
            // Lưu thông tin mới vào file
            System.IO.File.WriteAllText("class.json", jsonString);
            // Chuyển hướng về trang quản lý giáo viên
            return RedirectToAction("ManageClass");
        }
        [HttpPost]
        public IActionResult Save(Class @class)
        {
            var existingClass = classes.FirstOrDefault(t => t.Id == @class.Id);
            if (existingClass == null)
            {
                return NotFound(); // Trả về lỗi 404 nếu không tìm thấy giáo viên
            }

            // Cập nhật thông tin giáo viên
            existingClass.ClassName = @class.ClassName;
            existingClass.Major = @class.Major;
            existingClass.Lecturer = @class.Lecturer;

            var options = new JsonSerializerOptions { WriteIndented = true };
            string jsonString = JsonSerializer.Serialize(classes, options);

            // Lưu thông tin mới vào file
            System.IO.File.WriteAllText("class.json", jsonString);

            // Chuyển hướng về trang quản lý giáo viên
            return RedirectToAction("ManageClass");
        }
        [HttpGet] //click hyperlink
        public IActionResult Save()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Cancel(string returnUrl)
        {
            // Redirect to the ManageCourse action method
            return RedirectToAction("ManageClass");
        }
        [HttpGet] //click hyperlink
        public IActionResult EditClass(int id)
        {
            var @class = classes.FirstOrDefault(s => s.Id == id);
            if (@class == null)
            {
                return NotFound(); // Trả về lỗi 404 nếu không tìm thấy sinh viên
            }

            return View(@class);

        }
    }
}

SIMS_IT0602/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SIMS_IT0602.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SIMS_IT0602.Controllers
{
    public class TeacherController : Controller
    {
        static List<Teacher> teachers = new List<Teacher>();

        public IActionResult Delete(int Id)
        {
            var teachers = LoadTeacherFromFile("teacher.json");

            //find teacher in an array
            var searchTeacher = teachers.FirstOrDefault(t => t.Id == Id);
            teachers.Remove(searchTeacher);

            //save to file
            var options = new JsonSerializerOptions { WriteIndented = true };
            string jsonString = JsonSerializer.Serialize(teachers, options);
            //Save file
            using (StreamWriter writer = new StreamWriter("teacher.json"))
            {
                writer.Write(jsonString);
            }
            return RedirectToAction("ManageTeacher");

        }

        [HttpPost]
        public IActionResult Save(int Id,Teacher teacher)
        {
            var existingTeacher = teachers.FirstOrDefault(t => t.Id == teacher.Id);
            if (existingTeacher == null)
            {
                return NotFound(); // Trả về lỗi 404 nếu không tìm thấy giáo viên
            }

            // Cập nhật thông tin giáo viên
            existingTeacher.Name = teacher.Name;
            existingTeacher.DoB = teacher.DoB;
            existingTeacher.Course = teacher.Course;

            var options = new JsonSerializerOptions { WriteIndented = true };
            string jsonString = JsonSerializer.Serialize(teachers, options);

            // Lưu thông tin mới vào file
            System.IO.File.WriteAllText("teacher.json", jsonString);

            // Chuyển hướng về trang quản lý giáo viên
            return RedirectToAction("ManageTeacher");
        }

        [HttpPost] //submit new Teacher
        public IActionResult NewTeacher(Teacher teacher, List<Course> courses)
        {
            teachers.Add(teacher);
            var options = new JsonSerializerOptions { WriteIndented = true };
            string jsonString = JsonSerializer.Serialize(teachers, options);
            ViewBag.SelectCourse = new SelectList(courses, "Name", "Name");
            ViewBag.SelectCourse = courses;
            //Save file
            using (StreamWriter writer = new StreamWriter("teacher.json"))
            {
                writer.Write(jsonString);
            }

            return RedirectToAction("ManageTeacher", new { teachers = jsonString });
        }
        [HttpGet]
        public IActionResult NewTeacher()
        {
            List<Course> courses = LoadCourseFromFile("course.json");
            ViewBag.SelectCourse = courses;
            return View();
        }//click hyperlink
        public List<Course>? LoadCourseFromFile(string fileName)
        {
            string readText = System.IO.File.ReadAllText("course.json");
            return JsonSerializer.Deserialize<List<Course>>(readText);
        }
        public IActionResult Save(int Id)
        {
            return View();
        }
        [HttpPost]
        public IActionResult Edit(int Id, Teacher teacher, List<Course>courses)
        {
            var existingTeacher = teachers.FirstOrDefault(t => t.Id == teacher.Id);
            if (existingTeacher == null)
            {
                return NotFound(); // Trả về lỗi 404 nếu không tìm thấy giáo viên
            }
            teacher.Id = existingTeacher.Id;
            existingTeacher.Name = teacher.Name;
            existingTeacher.DoB = teacher.DoB;
            existingTeacher.Course = teacher.Course;

            var options = new JsonSerializerOptions { WriteIndented = true };
            string jsonString = JsonSerializer.Serialize(teachers, options);
            ViewBag.SelectCourse = courses;

            // Lưu thông tin mới vào file
            System.IO.File.WriteAllText("teacher.json", jsonString);


            // Chuyển hướng về trang quản lý giáo viên
            return RedirectToAction("ManageTeacher");
        }
        [HttpGet] //click hyperlink
        public IActionResult EditTeacher(int id)
        { 
            var teacher = teachers.FirstOrDefault(s => s.Id == id);
            if (teacher == null)
            {
                return NotFound(); // Trả về lỗi 404 nếu không tìm thấy sinh viên
            }
            List<Course> courses = LoadCourseFromFile("course.json");
            ViewBag.SelectCourse = courses;
            return View(teacher);
        }
    
        public List<Teacher>? LoadTeacherFromFile(string fileName)
        {
            string readText = System.IO.File.ReadAllText("teacher.json");
            return JsonSerializer.Deserialize<List<Teacher>>(readText);
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewBag.UserName = HttpContext.Session.GetString("UserName");
            ViewBag.Role = HttpContext.Session.GetString("Role");
            // Read a file
            teachers = LoadTeacherFromFile("teacher.json");
            return View(teachers);
        }
        
        public IActionResult ManageTeacher()
        {
            ViewBag.UserName = HttpContext.Session.GetString("UserName");
            ViewBag.Role = HttpContext.Session.GetString("Role");
          //  Read a file
           teachers = LoadTeacherFromFile("teacher.json");
            return View(teachers);
           // Trả về view Manageteacher.cshtml
         return View("Manageteacher");
        }
        public IActionResult ViewTeacher()
        {
            ViewBag.UserName = HttpContext.Session.GetString("UserName");
            ViewBag.Role = HttpContext.Session.GetString("Role");
            //  Read a file
            teachers = LoadTeacherFromFile("teacher.json");
            return View(teachers);
        }
        public IActionResult ViewClass()
        {
            // Xử lý logic để hiển thị thông tin lớp học
            return View();
        }

        [HttpPost]
        public ActionResult Cancel(string returnUrl)
        {
            // Redirect to the ManageCourse action method
            return RedirectToAction("ManageTeacher");
        }

        public IActionResult ViewCourse()
        {
            // Xử lý logic để hiển thị thông tin khóa học
            return View();
        }
        
    }
}

SIMS_IT0602/Views/Class/EditClass.cshtml
@model Class
@{
    ViewData["Title"] = " Edit Class";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}
<link href="~/Manage.css" rel="stylesheet" />
@section header {
    <header class="main-header clearfix" role="header">
        <div class="logo">
            <a href="#"><em>FPT</em> Polytechnic</a>
        </div>
        <a href="#menu" class="menu-link"><i class="fa fa-bars"></i></a>
        <nav id="menu" class="main-nav" role="navigation">
            <ul class="main-menu">
                <li><a href="/Admin/Index" class="external">Home</a></li>
                <li><a href="/Authentication/Logout" class="external">Logout</a></li>


            </ul>
        </nav>
    </header>
}
<section class="content">
    <h1 class="text-center" style="color: orange; margin-top:80px;">Edit Class</h1>

@using (Html.BeginForm("Save", "Class", FormMethod.Post))
{
    @Html.HiddenFor(m => m.Id)

    <div class="form-group">
        @Html.LabelFor(m => m.ClassName, new { Class = "control-label" })
        @Html.TextBoxFor(m => m.ClassName, new { Class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Major, new { Class = "control-label" })
        @Html.TextBoxFor(m => m.Major, new { Class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Lecturer, new { Class = "control-label" })
        @Html.TextBoxFor(m => m.Lecturer, new { Class = "form-control" })
    </div>
    <div class="form-group text-right">
        <!-- Đổi lớp form-group thành text-right để căn phải -->
        <button type="submit" class="btn btn-primary">Save</button>
        <button type="button" id="cancelBtn" class="btn btn-warning">Cancel</button>
    </div>

}
    <script>
        document.getElementById("cancelBtn").addEventListener("click", function () {
            window.location.href = "/Class/ManageClass";
        });
    </script>
    </section>

SIMS_IT0602/Views/Class/ManageClass.cshtml
@model IEnumerable<Class>
@{
    ViewData["Title"] = "Manage Class";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}
@* <link href="~/admin.css" rel="stylesheet" /> *@
@section header {
    <header class="main-header clearfix" role="header">
        <div class="logo">
            <a href="#"><em>FPT</em> Polytechnic</a>
        </div>
        <a href="#menu" class="menu-link"><i class="fa fa-bars"></i></a>
        <nav id="menu" class="main-nav" role="navigation">
            <ul class="main-menu">
            <li><a href="/Admin/Index"class="external">Home</a></li>
                <li><a href="/Student/ManageStudent" class="external">Student Management</a></li>
                <li><a href="/Course/ManageCourse" class="external">Courses Management</a></li>
                <li><a href="/Teacher/ManageTeacher" class="external">Teacher Management</a></li>
            <li><a href="/Authentication/Logout" class="external">Logout</a></li>


            </ul>
        </nav>
    </header>
}
<section class="content">
    <h1 class="text-center" style="color: orange; margin-top:80px;">Hello @ViewBag.UserName , You are @ViewBag.Role</h1>
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead class="bg-primary text-white">
                <tr>
                    <th class="text-center">ID</th>
                    <th class="text-center">Name</th>
                    <th class="text-center">Major</th>
                    <th class="text-center">Lecturer</th>
                    <th class="text-center">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td class="text-center">@item.Id</td>
                        <td class="text-center">@item.ClassName</td>
                        <td class="text-center">@item.Major</td>
                        <td class="text-center">@item.Lecturer</td>
                        <td class="text-center">
                            <div class="btn-group" role="group">
                                <a class="btn btn-danger mr-1" href="@Url.Action("Delete","Class",new {id=item.Id})">Delete</a>
                                <a class="btn btn-warning" href="@Url.Action("EditClass","Class",new {id=item.Id})">Edit</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <ul class="mt-3">
            <li>
                <a class="btn btn-success" asp-controller="Class" asp-action="NewClass">New Class</a>
            </li>
        </ul>
    </div>
</section>


    

SIMS_IT0602/Views/Class/NewClass.cshtml
@model Class
@{
    ViewData["Title"] = "Create Class";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}
<link href="~/Manage.css" rel="stylesheet" />
@section header {
    <header class="main-header clearfix" role="header">
        <div class="logo">
            <a href="#"><em>FPT</em> Polytechnic</a>
        </div>
        <a href="#menu" class="menu-link"><i class="fa fa-bars"></i></a>
        <nav id="menu" class="main-nav" role="navigation">
            <ul class="main-menu">
                <li><a href="/Admin/Index" class="external">Home</a></li>
                <li><a href="/Authentication/Logout" class="external">Logout</a></li>


            </ul>
        </nav>
    </header>
}
<section class="content">
<h1 class="text-center" style="color: orange; margin-top:80px;">New Class</h1>

@using (Html.BeginForm("NewClass", "Class", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Id, new { Class = "control-label" })
        @Html.TextBoxFor(m => m.Id, new { Class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.ClassName, new { Class = "control-label" })
        @Html.TextBoxFor(m => m.ClassName, new { Class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Major, new { Class = "control-label" })
        @Html.TextBoxFor(m => m.Major, new { Class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Lecturer, new { Class = "control-label" })
        @Html.TextBoxFor(m => m.Lecturer, new { Class = "form-control" })
    </div>
    <div class="form-group text-right">
    <input type="submit" value="Create Class" class="btn btn-primary" />
    <button type="button" id="cancelBtn" class="btn btn-warning">Cancel</button>
    </div>

}

    <script>
        document.getElementById("cancelBtn").addEventListener("click", function () {
            window.location.href = "/Class/ManageClass";
        });
    </script>
    </section>

SIMS_IT0602/Views/Class/ViewClass.cshtml
@{
    ViewData["Title"] = "ViewClass";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}
@model IEnumerable<Class>
<link href="~/User.css" rel="stylesheet" />
@section header {
    <header class="main-header clearfix" role="header">
        <div class="logo">
            <a href="#"><em>FPT</em> Polytechnic</a>
        </div>
        <a href="#menu" class="menu-link"><i class="fa fa-bars"></i></a>
        <nav id="menu" class="main-nav" role="navigation">
            <ul class="main-menu">
                <li><a href="/Authentication/Logout" class="external">Logout</a></li>


            </ul>
        </nav>
    </header>
}
<section class="content">
    <h1 class="text-center" style="color: orange; margin-top:60px;">Hello @ViewBag.UserName , Welcome @ViewBag.UserName to Classlist</h1>
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead class="bg-primary text-white">
        <tr>
            <td>ID</td>
            <td>Name</td>
            <td>Major</td>
            <td>Lecturer</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.ClassName</td>
                <td>@item.Major</td>
                <td>@item.Lecturer</td>
            </tr>
        }
    </tbody>
</table>
<ul>
    <li>
        <a class="btn btn-sm btn-primary" asp-controller="Teacher" asp-action="Index">Back to HomePage</a>
    </li>
</ul>
    </div>
</section>